name: CI

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Cache Packages
        id: cache-packages
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        if: steps.cache-packages.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lint with ESLint
        run: npm run lint:es
      - name: Lint format
        run: npm run lint:format
